### PR TITLE
Add timestamp field for XML result reports for minitest JUNIT reporters

### PR DESCRIPTION
**Pull request by sipani909**

### CODE REVIEW

**Comment by sipani909** [comment]
@itsliamegan can you please review this?

**Comment by sipani909** [comment]
@os97673 can you please look at this PR so that it can be merged?

**Comment by itsliamegan** [comment]
Thanks for your contribution!

First: please be patient when requesting feedback on an issue or PR. We are all volunteers, for whom maintaining `minitest-reporters` is not a full-time job, so we'll get to it when we can. Please don't @-mention people, especially those who aren't related to the project and won't appreciate a random GitHub notification.

About the implementation, a few notes:

- Most importantly, this needs to be an optional feature and disabled by default. I would assume that people using the existing XML export aren't expecting a timestamp field, which would break some parsing if it was included by default. As I suggested in my issue comment, an `include_timestamp` or other such parameter to the constructor for `JUnitReporter` which defaults to `false` should work.
- Use `Minitest::Reporters.clock_time` to get the current time. It's consistent with the existing code and will use process-safe functions if available.
- Report the timestamp using some standard format, probably ISO8601 which the Time class has a [nice method for](https://ruby-doc.org/stdlib-2.7.4/libdoc/time/rdoc/Time.html#method-c-iso8601).

Finally, please add your contribution to the CHANGELOG file under the "dev" heading, following the format of the existing entries.

**Comment by sipani909** [comment]
@itsliamegan Thank you for the pointers. Apologies for not following the guidelines. Will be careful going forward. 

For the  Minitest::Reporters.clock_time this reports monotonic time, for example, 4576.561734 in my tests which goes back to 1970 when I convert it. Can you please provide an example of using the method with the ISO 8601 standard?

Have added the rest of the suggestions.

**Comment by sipani909** [comment]
@itsliamegan can you please review the latest changeset?

**Comment by itsliamegan** [comment]
Whoops, seems like I was wrong on `#clock_time`, it's indented for comparisons (e.g. "how much time has elapsed since I last called `#clock_time`?"). Using `Time.now` is fine for that, then. To use the `Time#iso8601` method, add `require "time"` to the top of the (since it's a method on the stdlib `Time` class not the core one) and then call the method, i.e. `Time.now.iso8601`

**Comment by sipani909** [comment]
@itsliamegan Fixed and updated as requested!

**Comment by sipani909** [comment]
@itsliamegan Thank you so much for the approval! How do I get the gem to publish? I still see an old version here
https://rubygems.org/gems/minitest-reporters/versions

**Comment by itsliamegan** [comment]
I've got to make the release, which I can do tomorrow morning. I haven't cut a release in a while so it might take me a bit to set it up again.

**Comment by sipani909** [comment]
Thank you! Will pull the gem into my container once the release is cut.

**Comment by sipani909** [comment]
hi @itsliamegan can you please let me know once the release is cut for this PR?

**Comment by sipani909** [comment]
hi @itsliamegan can we please get this run through the release pipeline and publish the gem? This is blocking delivery of the code on our end else.

**Comment by sipani909** [comment]
@itsliamegan hi Liam, what is the status on the pipeline to publish the gem? I dont see it on the official gem page. Can you please run this so that I can pull this down?

**Comment by sipani909** [comment]
@itsliamegan can you please let me know a timeline for publishing the gem? 
It is frustrating having to wait on a gem publication for more than a month now after the code has been merged, and not knowing when the gem will be published. I understand that everyone is a volunteer here, but that should not block deliveries for this long.

**Comment by sipani909** [comment]
can someone please help with the gem publication here? CC @grosser @os97673

**Comment by grosser** [comment]
need to reach out to owners https://rubygems.org/gems/minitest-reporters

**Comment by sipani909** [comment]
yeah tagged @os97673 since he shows up as an owner. Also tagging @kern and @barrettkingram

**Comment by sipani909** [comment]
@kern, @barrettkingram Can you please advise on how to get this published for the gem? This has been blocking our code delivery for close to two months now.

**Comment by grosser** [comment]
might have to use a fork or try to contact via other channels 😞

**Comment by os97673** [comment]
I'm not working with ruby nowadays but will try to setup the environment and release a version over weekend

**Comment by itsliamegan** [comment]
[Version 1.5.0 is on RubyGems now](https://rubygems.org/gems/minitest-reporters/versions/1.5.0). For future reference, a handy feature of Bundler is depending on a gem from git rather than rubygems.org, i.e.

```ruby
# Gemfile

gem "minitest-reporters", git: "git://github.com/minitest-reporters/minitest-reporters.git"
```

**Comment by grosser** [comment]
thx for the release, want to add a new owner to rubygems so we don't have to bother you ? :)

**Comment by sipani909** [comment]
Thanks for the release! Was able to pull the gem today and rest with it!

**Pull request merged**
